#!/bin/bash
-rwxr--r-- 1 root root 16 May 10 12:59 0-current_working_directory
-rw-r--r-- 1 root root 15 May 10 13:18 1-listit
-rw-r--r-- 1 root root 17 May 10 13:26 2-bring_me_home
-rw-r--r-- 1 root root 31 May 10 12:39 README.md
